#!/bin/sh

RUN=$(pwd)
export GOPATH=$(pwd)
FN=bigpack-server.go
FO=bigpack-server

gofmt -w $FN
[ -f $FO ] && mv -f $FO $FO.old
# go build $FN

# build and strip all debug info
GOOS=linux go build -ldflags="-s -w" $FN

ERROR=$?
if [ $ERROR -ne 0 ]; then
    echo "Error $ERROR"
    # restore old working EXE
    [ -f $FO.old ] && mv -f $FO.old $FO
    exit $ERROR 
fi
chmod 555 $FO
rm -f $FO.old

# compress binary
# upx --brute $FO

./run
